### ISSUE TITLE
why it do not accept payement method from backend and does we need to setup aws to send mail  

### ISSUE THREAD

**Issue by shubhamchoudhary-2003** [aexol-studio/vendure-nextjs-storefront#33]
why it do not accept payement methid from backend and does we need to setup aws to send mail  
![Screenshot (106)](https://github.com/aexol-studio/vendure-nextjs-storefront/assets/130033575/7e287469-a30f-46f3-aea8-93b3d5c7c72d)
![Screenshot (104)](https://github.com/aexol-studio/vendure-nextjs-storefront/assets/130033575/814d9bc9-bbd6-4fee-832d-2055e1f7dec5)

**Comment by AleksanderBondar** [comment]
First of all I think You need to look on this line
https://github.com/aexol-studio/vendure-nextjs-storefront/blob/main/src/components/pages/checkout/components/OrderPayment.tsx#L66

**Comment by AleksanderBondar** [comment]
And about email You need to take a look on this guide:
https://docs.vendure.io/reference/core-plugins/email-plugin/
