### ISSUE TITLE
Sometimes back button is not working 

### ISSUE THREAD

**Issue by breathingcyborg** [aexol-studio/vendure-nextjs-storefront#34]
First, thanks for the starter template. Its really helpful.

Steps to reproduce the issue.
1. Navigate to home and garden in *new tab*. https://shop.aexol.com/collections/home-garden/
2. Click on filters and apply color: wood filter.
3. Click on the first product.
4. Navigate back using browser back button.

The URL is updated but the content is not.
Content is updated once you refresh the page.

Browsers
Chrome 110.0.5481.77 (Official Build) (64-bit) 
Firefox 122.0.1 (64-bit)

If you don't have time bandwidth to fix the issue, would you be able to provide any clues about what might be causing it? Your assistance would help a lot.

Thanks.

**Comment by AleksanderBondar** [comment]
Hello!

Yes of course I think it is caused beacuse of `history.pushState` try to replace it into `history.replaceState`. Hope it will works fine now ;)

**Comment by breathingcyborg** [comment]
Thanks for your help. 
I Forgot to close the issue :).
